title ="FP Dual Panel"
#tutor dashboard
recursosUtiles="Impulsa el desarrollo de tus aprendices con estos recursos"
documentacionTitle="Materiales de apoyo"
tabPreOnboarding="Antes de empezar"
tabOnboarding="Primeros Días"
tabSeguimiento="Seguimiento"
tabCierre="Cierre"
tutorDashboard="Recursos Útiles"
aprendizDashaboard="Reporte de mis aprendices"

adminRecursosTutorDashboard="Recursos Útiles"
adminTutorDashboard="Reporte General"

#login
username="Email"
password="Contraseña"
forgotPassword="Olvidé mi contraseña"
loginButton="Iniciar Sesión"
logoutButton="Desloguearse"
errorRedirection="Sesion expirada. Redirigiendo a login..."
IncorrectPassword="Email o contraseña incorrectos. Intente nuevamente"
logoutMessage="Deslogueo exitoso"
loginMessage="Sesión iniciada exitosamente"
loginDescription="Por favor, para comenzar inicie sesión"